### ISSUE TITLE
about template literals

### ISSUE THREAD

**Issue by olstenlarck** [airbnb/babel-preset-airbnb#30]
Looking at the code it seems that it is excluded, but later it's added again in the plugins array.

Why? I definitely read it carefully few times.

**Comment by lencioni** [comment]
I believe that it is excluded from the env preset here https://github.com/airbnb/babel-preset-airbnb/blob/97490058907cd350f7eab319ace84707f43e9ce5/index.js#L33-L37 so that it can be enabled here https://github.com/airbnb/babel-preset-airbnb/blob/97490058907cd350f7eab319ace84707f43e9ce5/index.js#L45-L47 with the `spec: true` option enabled.

It looks like this was brought over in https://github.com/airbnb/babel-preset-airbnb/pull/13

It is possible that we no longer need to do this or that we will soon no longer need to do this, but I'm not entirely sure. The documentation for that plugin does not mention this option anymore: https://new.babeljs.io/docs/en/next/babel-plugin-transform-template-literals.html

**Comment by olstenlarck** [comment]
Ahhh.. yea. Probably it's because that, make sense.
